### ISSUE TITLE
Please add hysteria to xray+Reality

### ISSUE THREAD

**Issue by Shjpr9** [lxhao61/integrated-examples#183]
Hi! Please add a config which has [hysteria v2](https://github.com/apernet/hysteria/releases/tag/app%2Fv2.0.0) as inbound then route it to a local xray inbound and use Reality as outbound.

[Hysteria documentation as you know is also here](https://v2.hysteria.network/zh/)

And this is an example server config for hysteria: [config.yaml](https://github.com/iSegaro/Hysteria.V2/blob/main/Server-Config)

This one is also an example of hysteria system file: [hy2.service](https://github.com/iSegaro/Hysteria.V2/blob/main/System-File)

Thank you for your time and effort.

**Comment by lxhao61** [comment]
你的想法不可能实现，当前 [Hysteria v2](https://v2.hysteria.network/zh/docs/advanced/Full-Server-Config/)  仅支持 url 转发。

**Comment by Shjpr9** [comment]
We have direct output which can be set via `bindIPv4`

```
outbounds:
  - name: hoho
    type: direct
    direct:
      mode: auto 
      bindIPv4: 2.4.6.8 
      bindIPv6: 0:0:0:0:0:ffff:0204:0608 
      bindDevice: eth233 
```

We also have "socks5" outbound which can be set via
```
outbounds:
  - name: socks-outbound
    type: socks5
    socks5:
      addr: 127.0.0.1:1080
      username: local
      password: local
```

And xray's inbound can be set with [this](https://xtls.github.io/config/inbounds/socks.html#inboundconfigurationobject)
